### ISSUE TITLE
randomly loads in the middle of the screen

### ISSUE THREAD

**Issue by ekko20six** [leonardopsantos/LunarSphere#7]
I have been having the issue for a few versions where when I first log in either the outer buttons or the whole add-on will load int he centre of my screen.
If I refresh UI it goes to where it is supposed to go
and sometimes it just loads where it is supposed to go
how do I troubleshoot?

**Comment by leonardopsantos** [comment]
Hi there!

Which client is this? Retail? Classic? TCC?

Does it show any Lua errors? One thing you could do is to try to figure out how to reliably reproduce the problem. Also, because of the way the WoW Lua API works, it's super easy for one add-on to interfere with another. Can you try disabling all other add-ons ad see if the problem goes away?

I don't really understand why the original authors are saving the sphere position, apparently calling `SetUserPlaced(true)` should make the game itself save LS's position and restore when appropriate. 

If you're not afraid of coding a little, I can help you place some debug messages.

Cheers!

**Comment by beren12** [comment]
I haven't had this happen in bcc.

**Comment by leonardopsantos** [comment]
Does this still happen in LS 1.58? For which client? Is there a way to trigger this problem or is it completely random?

**Comment by leonardopsantos** [comment]
Closing due to lack of feedback.
